=== api-evangelist/deliverect/json-schema/commerce-api-commerce-channel-api-baskets-update-basket-discounts-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/commerce-api-commerce-channel-api-baskets-update-basket-discounts-schema.json",
  "title": "CommerceChannelApiBasketsUpdateBasketDiscounts",
  "description": "discounts",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "example": "order_flat_off"
      },
      "provider": {
        "type": "string",
        "enum": [
          "restaurant",
          "coupon",
          "loyalty"
        ],
        "example": "coupon"
      },
      "amount": {
        "type": "integer",
        "format": "int32",
        "example": 100
      },
      "value": {
        "type": "integer",
        "format": "int32",
        "example": 1000
      },
      "name": {
        "type": "string",
        "example": "CONGRATS! HERE IS 1 EUR OFF"
      },
      "plu": {
        "type": "string",
        "example": "DLX-3"
      },
      "menuId": {
        "type": "string",
        "example": "668f7ff64dc853**c96**877"
      },
      "externalId": {
        "type": "string",
        "example": "discount-123",
        "nullable": true
      },
      "itemIds": {
        "type": "array",
        "items": {
          "type": "string",
          "example": "string"
        },
        "example": [
          "6900f2f01306779be71e7b8e"
        ]
      }
    },
    "required": [
      "type",
      "provider"
    ]
  }
}

=== api-evangelist/deliverect/examples/commerce-api-commerce-channel-api-baskets-update-basket-discounts-example.json
[
  {
    "type": "order_flat_off",
    "provider": "coupon",
    "amount": 100,
    "value": 1000,
    "name": "CONGRATS! HERE IS 1 EUR OFF",
    "plu": "DLX-3",
    "menuId": "668f7ff64dc853**c96**877",
    "externalId": "discount-123",
    "itemIds": [
      "6900f2f01306779be71e7b8e"
    ]
  }
]
