=== api-evangelist/deliverect/json-schema/commerce-api-commerce-channel-api-baskets-create-basket-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/commerce-api-commerce-channel-api-baskets-create-basket-schema.json",
  "title": "CommerceChannelApiBasketsCreateBasket",
  "description": "Deliverect Create Basket",
  "type": "object",
  "properties": {
    "channelLinkId": {
      "type": "string",
      "default": "",
      "example": "5e8abc11dec0001a009b",
      "description": "ID of the store the basket is happening for."
    },
    "fulfillment": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "pickup",
            "delivery",
            "eatIn",
            "dispatch"
          ],
          "default": "pickup",
          "example": "pickup"
        }
      },
      "required": [
        "type"
      ]
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "menuId": {
            "type": "string",
            "example": "609a1b2c3d4e5f6a7b8c9d0e"
          },
          "plu": {
            "type": "string",
            "default": "3F_COMBO",
            "example": "3F_COMBO"
          },
          "quantity": {
            "type": "integer",
            "format": "int32",
            "default": 2,
            "example": 2
          },
          "note": {
            "type": "string",
            "example": "No salad"
          },
          "subItems": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "plu": {
                  "type": "string",
                  "default": "A_FRS",
                  "example": "A_FRS"
                },
                "customizationPlu": {
                  "type": "string",
                  "example": "string"
                },
                "quantity": {
                  "type": "integer",
                  "format": "int32",
                  "default": 1,
                  "example": 1
                },
                "note": {
                  "type": "string",
                  "example": "No salad"
                }
              },
              "required": [
                "plu",
                "customizationPlu",
                "quantity"
              ]
            }
          }
        },
        "required": [
          "menuId",
          "plu",
          "quantity"
        ]
      }
    },
    "customer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Deliverect's Pizza Place"
        },
        "companyName": {
          "type": "string",
          "example": "Deliverect's Pizza Place"
        },
        "phoneNumber": {
          "type": "string",
          "example": "+15555550123"
        },
        "email": {
          "type": "string",
          "example": "customer@example.com"
        },
        "externalId": {
          "type": "string",
          "example": "609a1b2c3d4e5f6a7b8c9d0e"
        },
        "tin": {
          "type": "string",
          "example": "string"
        },
        "crmProfileId": {
          "type": "string",
          "example": "609a1b2c3d4e5f6a7b8c9d0e",
          "description": "If the order is to be assigned to a CRM customer, this fields needs to have a valid crmProfileId."
        }
      }
    }
  },
  "required": [
    "channelLinkId"
  ]
}

=== api-evangelist/deliverect/examples/commerce-api-commerce-channel-api-baskets-create-basket-example.json
{
  "channelLinkId": "5e8abc11dec0001a009b",
  "fulfillment": {
    "type": "pickup"
  },
  "items": [
    {
      "menuId": "609a1b2c3d4e5f6a7b8c9d0e",
      "plu": "3F_COMBO",
      "quantity": 2,
      "note": "No salad",
      "subItems": [
        {
          "plu": "A_FRS",
          "customizationPlu": "string",
          "quantity": 1,
          "note": "No salad"
        }
      ]
    }
  ],
  "customer": {
    "name": "Deliverect's Pizza Place",
    "companyName": "Deliverect's Pizza Place",
    "phoneNumber": "+15555550123",
    "email": "customer@example.com",
    "externalId": "609a1b2c3d4e5f6a7b8c9d0e",
    "tin": "string",
    "crmProfileId": "609a1b2c3d4e5f6a7b8c9d0e"
  }
}
