=== api-evangelist/deliverect/json-schema/crm-api-post-crm-accountid-customers-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/crm-api-post-crm-accountid-customers-schema.json",
  "title": "PostCrmAccountidCustomers",
  "description": "Deliverect Create Customer",
  "type": "object",
  "properties": {
    "contact": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "example": "customer@example.com"
        },
        "firstName": {
          "type": "string",
          "example": "Deliverect's Pizza Place"
        },
        "lastName": {
          "type": "string",
          "example": "Deliverect's Pizza Place"
        },
        "birthdate": {
          "type": "string",
          "example": "2026-03-15T14:30:00Z"
        },
        "phone": {
          "type": "string",
          "example": "+15555550123"
        }
      },
      "required": [
        "email"
      ]
    },
    "externalId": {
      "type": "string",
      "example": "609a1b2c3d4e5f6a7b8c9d0e"
    },
    "loyaltyProviderId": {
      "type": "string",
      "example": "609a1b2c3d4e5f6a7b8c9d0e"
    },
    "deliveryAddresses": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "street": {
            "type": "string",
            "example": "string"
          },
          "subpremise": {
            "type": "string",
            "example": "string"
          },
          "city": {
            "type": "string",
            "example": "string"
          },
          "stateOrProvince": {
            "type": "string",
            "example": "string"
          },
          "postalCode": {
            "type": "string",
            "example": "string"
          },
          "country": {
            "type": "string",
            "example": "BE"
          },
          "default": {
            "type": "boolean",
            "example": true
          },
          "area": {
            "type": "string",
            "example": "string"
          },
          "coordinates": {
            "type": "array",
            "items": {
              "type": "number",
              "format": "float",
              "example": 1.0
            }
          }
        }
      }
    },
    "billingAddress": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string",
          "example": "string"
        },
        "subpremise": {
          "type": "string",
          "example": "string"
        },
        "city": {
          "type": "string",
          "example": "string"
        },
        "stateOrProvince": {
          "type": "string",
          "example": "string"
        },
        "postalCode": {
          "type": "string",
          "example": "string"
        },
        "country": {
          "type": "string",
          "example": "BE"
        },
        "area": {
          "type": "string",
          "example": "string"
        },
        "coordinates": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float",
            "example": 1.0
          }
        }
      }
    },
    "metadata": {
      "type": "object",
      "properties": {}
    },
    "vehicles": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "make": {
            "type": "string",
            "example": "string"
          },
          "model": {
            "type": "string",
            "example": "string"
          },
          "color": {
            "type": "string",
            "example": "string"
          },
          "default": {
            "type": "boolean",
            "example": true
          }
        }
      }
    }
  },
  "required": [
    "contact"
  ]
}

=== api-evangelist/deliverect/examples/crm-api-post-crm-accountid-customers-example.json
{
  "contact": {
    "email": "customer@example.com",
    "firstName": "Deliverect's Pizza Place",
    "lastName": "Deliverect's Pizza Place",
    "birthdate": "2026-03-15T14:30:00Z",
    "phone": "+15555550123"
  },
  "externalId": "609a1b2c3d4e5f6a7b8c9d0e",
  "loyaltyProviderId": "609a1b2c3d4e5f6a7b8c9d0e",
  "deliveryAddresses": [
    {
      "street": "string",
      "subpremise": "string",
      "city": "string",
      "stateOrProvince": "string",
      "postalCode": "string",
      "country": "BE",
      "default": true,
      "area": "string",
      "coordinates": [
        1.0
      ]
    }
  ],
  "billingAddress": {
    "street": "string",
    "subpremise": "string",
    "city": "string",
    "stateOrProvince": "string",
    "postalCode": "string",
    "country": "BE",
    "area": "string",
    "coordinates": [
      1.0
    ]
  },
  "metadata": {},
  "vehicles": [
    {
      "make": "string",
      "model": "string",
      "color": "string",
      "default": true
    }
  ]
}
