=== api-evangelist/deliverect/json-schema/dispatch-api-dispatch-create-job-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/dispatch-api-dispatch-create-job-schema.json",
  "title": "DispatchCreateJob",
  "description": "Deliverect Create Delivery Job",
  "type": "object",
  "properties": {
    "jobId": {
      "type": "string",
      "example": "609***72e"
    },
    "account": {
      "type": "string",
      "example": "5f1***131"
    },
    "pickupTime": {
      "type": "string",
      "format": "date-time",
      "example": "2021-05-13T13:40:04Z"
    },
    "transportType": {
      "type": "string",
      "example": "unknown"
    },
    "driverTip": {
      "type": "integer",
      "example": 500
    },
    "pickupLocation": {
      "type": "object",
      "properties": {
        "location": {
          "type": "string",
          "example": "606***555"
        },
        "name": {
          "type": "string",
          "example": "Deliverects Pizza Place"
        },
        "remarks": {
          "type": "string",
          "example": "please use the backdoor for order pickup"
        },
        "street": {
          "type": "string",
          "example": "van Ghentlaan"
        },
        "streetNumber": {
          "type": "string",
          "example": "3"
        },
        "postalCode": {
          "type": "string",
          "example": "9000 LK"
        },
        "city": {
          "type": "string",
          "example": "Leusden"
        },
        "latitude": {
          "type": "string",
          "example": "52.379189"
        },
        "longitude": {
          "type": "string",
          "example": "4.899431"
        }
      }
    },
    "deliveryLocations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "orderId": {
            "type": "string",
            "example": "609***4dd"
          },
          "channelOrderDisplayId": {
            "type": "string",
            "example": "MT4YVTPL"
          },
          "deliveryTime": {
            "type": "string",
            "format": "date-time",
            "example": "2021-05-13T13:55:00Z"
          },
          "packageSize": {
            "type": "string",
            "example": "medium"
          },
          "orderDescription": {
            "type": "string",
            "example": "hot food"
          },
          "company": {
            "type": "string",
            "example": "BrainQuantums"
          },
          "name": {
            "type": "string",
            "example": "V. Bertels"
          },
          "street": {
            "type": "string",
            "example": "Refugehof"
          },
          "streetNumber": {
            "type": "string",
            "example": "49"
          },
          "postalCode": {
            "type": "string",
            "example": "9001 AB"
          },
          "city": {
            "type": "string",
            "example": "Leusden"
          },
          "phone": {
            "type": "string",
            "example": "+32123456789"
          },
          "phoneAccessCode": {
            "type": "string",
            "example": "342241214"
          },
          "deliveryRemarks": {
            "type": "string",
            "example": "Dont ring door bell."
          },
          "latitude": {
            "type": "string",
            "example": "52.379189"
          },
          "longitude": {
            "type": "string",
            "example": "4.899431"
          },
          "payment": {
            "type": "object",
            "properties": {
              "orderIsAlreadyPaid": {
                "type": "boolean",
                "example": true
              },
              "amount": {
                "type": "integer",
                "example": 1100
              },
              "paymentType": {
                "type": "integer",
                "example": 0
              }
            }
          }
        }
      }
    },
    "ageCheck": {
      "type": "boolean",
      "example": false
    }
  }
}

=== api-evangelist/deliverect/examples/dispatch-api-dispatch-create-job-example.json
{
  "jobId": "609***72e",
  "account": "5f1***131",
  "pickupTime": "2021-05-13T13:40:04Z",
  "transportType": "unknown",
  "driverTip": 500,
  "pickupLocation": {
    "location": "606***555",
    "name": "Deliverects Pizza Place",
    "remarks": "please use the backdoor for order pickup",
    "street": "van Ghentlaan",
    "streetNumber": "3",
    "postalCode": "9000 LK",
    "city": "Leusden",
    "latitude": "52.379189",
    "longitude": "4.899431"
  },
  "deliveryLocations": [
    {
      "orderId": "609***4dd",
      "channelOrderDisplayId": "MT4YVTPL",
      "deliveryTime": "2021-05-13T13:55:00Z",
      "packageSize": "medium",
      "orderDescription": "hot food",
      "company": "BrainQuantums",
      "name": "V. Bertels",
      "street": "Refugehof",
      "streetNumber": "49",
      "postalCode": "9001 AB",
      "city": "Leusden",
      "phone": "+32123456789",
      "phoneAccessCode": "342241214",
      "deliveryRemarks": "Dont ring door bell.",
      "latitude": "52.379189",
      "longitude": "4.899431",
      "payment": {
        "orderIsAlreadyPaid": true,
        "amount": 1100,
        "paymentType": 0
      }
    }
  ],
  "ageCheck": false
}
