=== api-evangelist/deliverect/json-schema/pay-api-pay-endpoints-request-payment-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/pay-api-pay-endpoints-request-payment-schema.json",
  "title": "PayEndpointsRequestPayment",
  "description": "Deliverect Request Payment",
  "type": "object",
  "properties": {
    "gatewayProfileId": {
      "type": "string",
      "example": "609a1b2c3d4e5f6a7b8c9d0e",
      "description": "\"id\" retrieved via Get Payment Gateways endpoint"
    },
    "mode": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "offline",
            "redirect",
            "terminal",
            "token"
          ],
          "example": "offline"
        },
        "returnUrl": {
          "type": "string",
          "example": "https://example.com/path/abc123"
        },
        "tokenId": {
          "type": "string",
          "example": "609a1b2c3d4e5f6a7b8c9d0e",
          "description": "\"id\" retrieved via [Get Customer Tokens endpoint](https://developers.deliverect.com/reference/pay_endpoints-get-customer-tokens). Used only when `type=\"token\"`"
        }
      }
    },
    "amount": {
      "type": "integer",
      "format": "int32",
      "example": 1250
    },
    "currency": {
      "type": "string",
      "example": "EUR"
    },
    "payableReference": {
      "type": "string",
      "example": "string",
      "description": "This field is deprecated. Use the `payable` field instead."
    },
    "payer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Deliverect's Pizza Place"
        },
        "email": {
          "type": "string",
          "example": "customer@example.com"
        },
        "reference": {
          "type": "string",
          "example": "string"
        },
        "ip": {
          "type": "string",
          "example": "string",
          "description": "The payer's IP address"
        }
      }
    },
    "payable": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "609a1b2c3d4e5f6a7b8c9d0e",
          "description": "A unique reference to the payable subject."
        }
      }
    },
    "billingAddress": {
      "type": "object",
      "properties": {
        "country": {
          "type": "string",
          "example": "BE"
        },
        "city": {
          "type": "string",
          "example": "string"
        },
        "postalCode": {
          "type": "string",
          "example": "string"
        },
        "street": {
          "type": "string",
          "example": "string"
        },
        "houseNumber": {
          "type": "string",
          "example": "string"
        },
        "stateOrProvince": {
          "type": "string",
          "example": "string"
        }
      }
    },
    "captureMode": {
      "type": "string",
      "enum": [
        "immediate",
        "manual"
      ],
      "default": "immediate",
      "example": "immediate"
    }
  },
  "required": [
    "gatewayProfileId",
    "mode",
    "amount",
    "currency",
    "payable"
  ]
}

=== api-evangelist/deliverect/examples/pay-api-pay-endpoints-request-payment-example.json
{
  "gatewayProfileId": "609a1b2c3d4e5f6a7b8c9d0e",
  "mode": {
    "type": "offline",
    "returnUrl": "https://example.com/path/abc123",
    "tokenId": "609a1b2c3d4e5f6a7b8c9d0e"
  },
  "amount": 1250,
  "currency": "EUR",
  "payableReference": "string",
  "payer": {
    "name": "Deliverect's Pizza Place",
    "email": "customer@example.com",
    "reference": "string",
    "ip": "string"
  },
  "payable": {
    "id": "609a1b2c3d4e5f6a7b8c9d0e"
  },
  "billingAddress": {
    "country": "BE",
    "city": "string",
    "postalCode": "string",
    "street": "string",
    "houseNumber": "string",
    "stateOrProvince": "string"
  },
  "captureMode": "immediate"
}
