=== api-evangelist/deliverect/json-schema/pay-api-payplatform-payments-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/pay-api-payplatform-payments-request-schema.json",
  "title": "PayplatformPaymentsRequest",
  "description": "Deliverect Request Payment",
  "type": "object",
  "properties": {
    "gatewayProfileId": {
      "type": "string",
      "example": "609a1b2c3d4e5f6a7b8c9d0e"
    },
    "amount": {
      "type": "integer",
      "format": "int32",
      "example": 1250
    },
    "currency": {
      "type": "string",
      "example": "EUR"
    },
    "returnUrl": {
      "type": "string",
      "example": "https://example.com/path/abc123"
    },
    "reference": {
      "type": "string",
      "example": "string"
    },
    "logoUrl": {
      "type": "string",
      "example": "https://example.com/path/abc123"
    },
    "payer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Deliverect's Pizza Place"
        },
        "email": {
          "type": "string",
          "example": "customer@example.com"
        },
        "reference": {
          "type": "string",
          "example": "string"
        }
      }
    }
  },
  "required": [
    "gatewayProfileId",
    "amount",
    "currency",
    "returnUrl",
    "reference"
  ]
}

=== api-evangelist/deliverect/examples/pay-api-payplatform-payments-request-example.json
{
  "gatewayProfileId": "609a1b2c3d4e5f6a7b8c9d0e",
  "amount": 1250,
  "currency": "EUR",
  "returnUrl": "https://example.com/path/abc123",
  "reference": "string",
  "logoUrl": "https://example.com/path/abc123",
  "payer": {
    "name": "Deliverect's Pizza Place",
    "email": "customer@example.com",
    "reference": "string"
  }
}
