=== api-evangelist/deliverect/json-schema/pos-api-pos-api-product-sync-callback-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/deliverect/refs/heads/main/json-schema/pos-api-pos-api-product-sync-callback-schema.json",
  "title": "PosApiProductSyncCallback",
  "description": "Deliverect Asynchronous Insert / Update Products",
  "type": "object",
  "properties": {
    "operationReportId": {
      "type": "string",
      "example": "507f****************9011"
    },
    "products": {
      "type": "object",
      "properties": {
        "inserted": {
          "type": "integer",
          "example": 1
        },
        "updated": {
          "type": "integer",
          "example": 0
        },
        "deleted": {
          "type": "integer",
          "example": 0
        },
        "ignored": {
          "type": "integer",
          "example": 0
        }
      }
    },
    "modifiers": {
      "type": "object",
      "properties": {
        "inserted": {
          "type": "integer",
          "example": 6
        },
        "updated": {
          "type": "integer",
          "example": 0
        },
        "deleted": {
          "type": "integer",
          "example": 0
        },
        "ignored": {
          "type": "integer",
          "example": 0
        }
      }
    },
    "modifierGroups": {
      "type": "object",
      "properties": {
        "inserted": {
          "type": "integer",
          "example": 2
        },
        "updated": {
          "type": "integer",
          "example": 0
        },
        "deleted": {
          "type": "integer",
          "example": 0
        },
        "ignored": {
          "type": "integer",
          "example": 0
        }
      }
    },
    "bundles": {
      "type": "object",
      "properties": {
        "inserted": {
          "type": "integer",
          "example": 0
        },
        "updated": {
          "type": "integer",
          "example": 0
        },
        "deleted": {
          "type": "integer",
          "example": 0
        },
        "ignored": {
          "type": "integer",
          "example": 0
        }
      }
    },
    "priceLevels": {
      "type": "integer",
      "example": 0
    },
    "warnings": {
      "type": "integer",
      "example": 0
    },
    "errors": {
      "type": "integer",
      "example": 0
    }
  }
}

=== api-evangelist/deliverect/examples/pos-api-pos-api-product-sync-callback-example.json
{
  "operationReportId": "507f****************9011",
  "products": {
    "inserted": 1,
    "updated": 0,
    "deleted": 0,
    "ignored": 0
  },
  "modifiers": {
    "inserted": 6,
    "updated": 0,
    "deleted": 0,
    "ignored": 0
  },
  "modifierGroups": {
    "inserted": 2,
    "updated": 0,
    "deleted": 0,
    "ignored": 0
  },
  "bundles": {
    "inserted": 0,
    "updated": 0,
    "deleted": 0,
    "ignored": 0
  },
  "priceLevels": 0,
  "warnings": 0,
  "errors": 0
}
